[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smartsheet-weekly-reporter"
version = "1.0.0"
description = "Fetch tasks from Smartsheet for the specified week and formats them for easy pasting straight into PowerPoint slides."
authors = [{ name = "wyatthoho", email = "wyatthoho@gmail.com" }]
dependencies = [
    "python-dotenv >= 1.2.2",
    "smartsheet-python-sdk >= 3.0.0",
    "streamlit>=1.30.0",
    "tzdata >= 2024.1",
]
requires-python = ">=3.12"
readme = "README.md"
license = { file = "LICENSE" }

[project.scripts]
weekly-report = "weekly_report.main:main"

[tool.setuptools]
package-dir = { "" = "src" }

[project.optional-dependencies]
dev = ["pytest >= 8.3.4"]
